version: 0.2
phases:
  install:
    runtime-versions:
      php: latest
    commands:
      - echo Commands...
      - npm install -g mocha
  pre_build:
    commands:  
      - npm install 
      - docker login -u aldigitalcol -p dckr_pat_9dkaNTLxApRd0FkfagHAptgGRYM
  build:
    commands:
      - echo Build started on `date`
      - docker build -t aldigitalcol/mastertools-link-analytics:latest -f Dockerfile .
  post_build:
    commands:
      - docker push aldigitalcol/mastertools-link-analytics:latest
      - printf '[{"name":"link-analytics-app-dev-task","imageUri":"%s"}]' aldigitalcol/mastertools-link-analytics:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json