version: 0.2
env: 
  USER_DOCKER: "aldigitalcol"
  PASS_DOCKER: "dckr_pat_9dkaNTLxApRd0FkfagHAptgGRYM"
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Commands...
      - npm install -g mocha
  pre_build:
    commands:  
      - npm install 
      -  docker login --username "$USER_DOCKER" -p "$PASS_DOCKER"
      - REPOSITORY_URI=aldigitalcol/mastertools-link-analytics:latest
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:main -f Dockerfile .
      - docker tag latest
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"links-analytics-new-app-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json