version: 0.2
env: 
    USER_DOCKER: "aldigitalcol"
    PASS_DOCKER: "dckr_pat_9dkaNTLxApRd0FkfagHAptgGRYM"
phases:
  install:
    commands:
    - echo No commands...
     # Start Mysql if you need it
     # - apt-get install -y mysql-server
     # - su mysql -s /bin/bash -c "/usr/sbin/mysqld" &
  pre_build:
    commands:    
      - echo "$PASS_DOCKER" | docker login --username "$USER_DOCKER" --password-stdin
      - REPOSITORY_URI=aldigitalcol/mastertools-link-analytics:latest
  build:
    commands:
      - docker build -t $REPOSITORY_URI:main -f Dockerfile .
      - docker tag latest
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"links-analytics-new-app-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json