version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Commands...
  pre_build:
    commands:  
      - docker login --username "aldigitalcol" --password-stdin "dckr_pat_9dkaNTLxApRd0FkfagHAptgGRYM"
      - REPOSITORY_URI=aldigitalcol/mastertools-link-analytics:latest
  build:
    commands:
      - npm run test
      - docker build -t $REPOSITORY_URI:main -f Dockerfile .
      - docker tag latest
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"links-analytics-new-app-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json