version: '2'

services: 
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: link-analytics
    restart: always
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - './html/:/var/www/html'
